# Site wide configuration

title: Donald Hutchison
locale: en_US
description: Personal Blog of Donald Hutchison featuring nonsense and software
logo: site-logo.png
search: true
#url: www.donaldhutchison.info


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Donald Hutchison
  avatar: bio-photo.jpg
  email: contact@donaldhutchison.info
  disqus-shortname: "donaldhutchisoninfo"
  twitter: rev_kachowski
  facebook: #username
  keybase:    "https://keybase.io/rkachowski"
  github: rkachowski
  stackexchange: "https://careers.stackoverflow.com/donaldhutchison" 
  linkedin: "https://www.linkedin.com/pub/donald-hutchison/22/a70/16a"
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-17488316-1
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
